var anwser=require('./calculate.js');
var expect=require('chai').expect;

describe('js计算器测试',function(){
	it('1+1=2',function(){
		expect(anwser("1+1")).to.be.equal(2);
	});
	it('-5+1000=995',function(){
		expect(anwser("-5+1000")).to.be.equal(995);
	});
	it('(-2)+(-3)=-5',function(){
		expect(anwser("(-2)+(-3)")).to.be.equal(-5);
	});
	it('0+1=1',function(){
		expect(anwser("0+1")).to.be.equal(1);
	});
	it('24-8=16',function(){
		expect(anwser("24-8")).to.be.equal(16);
	});
	it('(-5)-(-4)=-1)',function(){
		expect(anwser("(-5)-(-4)")).to.be.equal(-1);
	});
	it('8-(-8)=16',function(){
		expect(anwser("8-(-8)")).to.be.equal(16);
	});
	it('5-0=5',function(){
		expect(anwser("5-0")).to.be.equal(5);
	});
	it('(-5)-4=-9',function(){
		expect(anwser("(-5)-4")).to.be.equal(-9);
	});
	it('3*2=6',function(){
		expect(anwser("3*2")).to.be.equal(6);
	});
	it('3*1=3',function(){
		expect(anwser("3*1")).to.be.equal(3);
	});
	it('(-3)*(-1)=3)',function(){
		expect(anwser("(-3)*(-1)")).to.be.equal(3);
	});
	it('(-3)*1=-3)',function(){
		expect(anwser("(-3)*1")).to.be.equal(-3);
	});
	it('0*0=0',function(){
		expect(anwser("0*0")).to.be.equal(0);
	});
	it('0*3=0',function(){
		expect(anwser("0*3")).to.be.equal(0);
	});
	it('0*(-3)=0',function(){
		expect(anwser("0*(-3)")).to.be.equal(0);
	});
	it('6/2=3',function(){
		expect(anwser("6/2")).to.be.equal(3);
	});
	it('-6/2=-3',function(){
		expect(anwser("-6/2")).to.be.equal(-3);
	});
	it('6/0=ERROR',function(){
		expect(anwser("6/0")).to.be.equal("ERROR");
	});
	it('0/6=0',function(){
		expect(anwser("0/6")).to.be.equal(0);
	});
	it('6/1=6',function(){
		expect(anwser("6/1")).to.be.equal(6);
	});
	it('5!=120',function(){
		expect(anwser("5!")).to.be.equal(120);
	});
	it('0!=1',function(){
		expect(anwser("0！")).to.be.equal(1);
	});
	it('(-3)!=ERROR',function(){
		expect(anwser("(-3)!")).to.be.equal("ERROR");
	});
	it('1!=1',function(){
		expect(anwser("1!")).to.be.equal(1);
	});
	it('(5*(3+2)+1)*2=52',function(){
		expect(anwser("(5*(3+2)+1)*2")).to.be.equal(52);
	});
	it('(2*(3/(2+1))+3)/5=1',function(){
		expect(anwser("(2*(3/(2+1))+3)/5")).to.be.equal(1);
	});
	it('3*(5/(3+2))=3',function(){
		expect(anwser("3*(5/(3+2))")).to.be.equal(3);
	});
	it('6/(0+6)=1',function(){
		expect(anwser("6/(0+6)")).to.be.equal(1);
	});
	it('3-(5-2)=0',function(){
		expect(anwser("3-(5-2)")).to.be.equal(0);
	});
});